##consul服务端口号
server:
  port: 8081
spring:
  application:
    name: cloud-consumer-order
  #sonsul注册中心地址
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #hostname: 127.0.0.1
        #healthCheckPath: /actuator/health
        #healthCheckInterval: 5s